GAMEPAD_DPAD_UP add volume 2
GAMEPAD_DPAD_DOWN add volume -2
GAMEPAD_DPAD_LEFT seek -10
GAMEPAD_DPAD_RIGHT seek 10

GAMEPAD_ACTION_RIGHT cycle pause
GAMEPAD_ACTION_DOWN add brightness -1
GAMEPAD_ACTION_LEFT add brightness 1
GAMEPAD_ACTION_UP cycle mute

GAMEPAD_LEFT_SHOULDER add panscan -0.1
GAMEPAD_RIGHT_SHOULDER add panscan +0.1

GAMEPAD_LEFT_TRIGGER playlist-prev
GAMEPAD_RIGHT_TRIGGER playlist-next

GAMEPAD_BACK quit-watch-later
GAMEPAD_START cycle pause